# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Physical Therapy Boulder, Broomfield, Westminster | Bodywise Physical Therapy
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Bodywise Physical Therapy is committed to offering the highest level of physical therapy treatment to patients in Boulder, Broomfield, and Westminster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
collections:
  team-members:
    title: Team Members
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    layout: post
    image: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Build settings
markdown: kramdown
permalink: pretty
include:
- _redirects
plugins:
- jekyll-feed
- jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
